# Proyecto - Limpieza de datos realistas

Utilizando un codigo en Python, previamente se generó una base de datos realista para hacer limpieza.

In [53]:
# Importando librerias pandas y numpy
import pandas as pd
import numpy as np

In [54]:
# Localización absoluta de la libreta
import os
os.getcwd()

'C:\\Users\\lego_\\Documents'

In [61]:
# Localizacion de los archivos
file_name1 = "C:\\Users\\lego_\\Documents\\orders_dirty.csv"
file_name2 = "C:\\Users\\lego_\\Documents\\products_dirty.csv"
file_name3 = "C:\\Users\\lego_\\Documents\\customers_dirty.csv"

<h2> Limpieza para la tabla "Orders" </h2>

In [62]:
#Data frame "orders"
df_ord = pd.read_csv(file_name1)
df_ord.head()

,order_id,customer_id,product_id,order_date,quantity,price,total_amount
0,1,123,6,2023-03-31,1,355.49,355.49
1,2,27,3,2023-12-10,1,357.01,357.01
2,3,139,10,2023-12-16,2,134.30,268.60
3,4,73,16,2023-04-13,3,374.66,1123.98
4,5,179,1,2023-10-25,2,300.03,30003.00

### Primero cambiamos los titulos

In [63]:
#Cambiamos los títulos
df_ord.rename(columns = {'order_id':'Order_ID', 'customer_id':'Customer_ID', 'product_id':'Product_ID',
                         'order_date':'Order_date', 'quantity':'Quantity','price':'Price',
                         'total_amount':'Total_amount'})

,Order_ID,Customer_ID,Product_ID,Order_date,Quantity,Price,Total_amount
0,1,123,6,2023-03-31,1,355.49,355.49
1,2,27,3,2023-12-10,1,357.01,357.01
2,3,139,10,2023-12-16,2,134.30,268.60
3,4,73,16,2023-04-13,3,374.66,1123.98
4,5,179,1,2023-10-25,2,300.03,30003.00
...,...,...,...,...,...,...,...
2555,1285,39,18,2023-03-10,2,126.38,252.76
2556,238,180,11,2023-06-28,3,208.55,625.65
2557,636,216,7,2023-02-16,3,131.87,395.61
2558,1007,220,4,2023-03-15,1,246.02,246.02
2559,1375,18,5,2023-10-05,1,195.21,195.21

In [64]:
#"orders" info
df_ord.info()

<class 'pandas.DataFrame'>
RangeIndex: 2560 entries, 0 to 2559
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2560 non-null   int64
 1   customer_id   2560 non-null   int64
 2   product_id    2560 non-null   int64
 3   order_date    2560 non-null   str
 4   quantity      2560 non-null   int64
 5   price         2560 non-null   float64
 6   total_amount  2456 non-null   float64
dtypes: float64(2), int64(4), str(1)
memory usage: 140.1 KB

Con esto notamos que hay valores nulos en "Total_amount".

In [65]:
#"orders" tipos de dato
df_ord.dtypes

order_id          int64
customer_id       int64
product_id        int64
order_date          str
quantity          int64
price           float64
total_amount    float64
dtype: object

In [66]:
#"orders" valores estadisticos
df_ord.describe()

,order_id,customer_id,product_id,quantity,price,total_amount
count,2560.000000,2560.000000,2560.000000,2560.000000,2560.000000,2456.000000
mean,1247.458594,149.430469,10.275781,1.993359,222.041852,510.250619
std,721.041258,86.678566,5.771109,0.821955,126.224316,1491.996797
min,1.000000,1.000000,1.000000,1.000000,-50.000000,-7500.000000
25%,623.750000,72.000000,5.000000,1.000000,171.820000,222.880000
50%,1247.500000,149.000000,10.000000,2.000000,208.550000,390.420000
75%,1871.250000,226.000000,15.000000,3.000000,343.710000,668.640000
max,2500.000000,300.000000,20.000000,3.000000,413.170000,41317.000000

Podemos notar que el máx en "total_amount" es mayor a 40000, cuando el precio más alto de un item es menor a 500 y la cantidad comprada es máximo 3, lo que es incosistente. También notamos que hay valores negativos en "price".

Buscamos los valores donde el precio es negativo:

In [67]:
df_ord.query("price < 0")

,order_id,customer_id,product_id,order_date,quantity,price,total_amount
26,27,28,13,2023-08-25,2,-50.0,-100.0
27,28,112,12,2023-09-16,2,-50.0,-100.0
28,29,141,12,2023-12-09,2,-50.0,-100.0
39,40,65,13,2023-08-19,1,-50.0,-50.0
62,63,40,13,2026-01-01,3,-50.0,-150.0
...,...,...,...,...,...,...,...
2511,1283,134,13,2023-05-16,3,-50.0,-150.0
2514,1576,4,12,2023-02-28,3,-50.0,-150.0
2531,633,9,12,2023-06-20,2,-50.0,-100.0
2538,133,166,12,2023-03-08,1,-50.0,-50.0
2540,202,136,12,2023-12-22,1,-50.0,-50.0

In [73]:
neg_vals = df_ord.query("price < 0")["product_id"]
neg_vals.unique()

array([13, 12])

In [79]:
df_ord.query('product_id in [12,13] and price>0')

Empty DataFrame
Columns: [order_id, customer_id, product_id, order_date, quantity, price, total_amount]
Index: []

Todos artículos con "product_id" 12 y 13 tienen precios negativos. A falta de más información, los removemos.

In [81]:
df_ord = df_ord.query('price>0')

Corregimos los valores en "total_amount".

In [82]:
df_ord['total_amount'] = df_ord['price']*df_ord['quantity']

Hemos realizamos el calculo correctamente.

Convertimos los datos de tipo "string" a "datatime":

In [83]:
df_ord["order_date"] = pd.to_datetime(df_ord["order_date"])

In [84]:
df_ord.dtypes

order_id                 int64
customer_id              int64
product_id               int64
order_date      datetime64[us]
quantity                 int64
price                  float64
total_amount           float64
dtype: object

In [85]:
len(df_ord[df_ord["order_date"] > pd.Timestamp.today()])

0

Consultamos las fechas posteriores a la fecha de hoy (2026-04-30), lo que muestra que <b>no</b> hay fechas con valores futuros

### Buscamos los valores nulos y duplicados

In [86]:
df_ord.isna().sum()

order_id        0
customer_id     0
product_id      0
order_date      0
quantity        0
price           0
total_amount    0
dtype: int64

No hay más valores faltantes en "total_amount". Buscamos valores duplicados:

In [87]:
df_ord.loc[df_ord.duplicated()]

,order_id,customer_id,product_id,order_date,quantity,price,total_amount
2500,507,250,15,2023-06-28,1,413.17,413.17
2502,355,117,18,2023-09-09,3,126.38,379.14
2503,1081,17,5,2023-01-02,1,195.21,195.21
2504,2390,72,17,2023-01-29,1,343.71,343.71
2505,1643,200,2,2023-02-25,1,181.61,181.61
2506,1569,229,20,2023-02-02,1,244.08,244.08
2507,636,216,7,2023-02-16,3,131.87,395.61
2508,2363,70,5,2023-08-07,1,195.21,195.21
2509,1742,260,3,2023-03-11,3,357.01,1071.03
2510,1564,286,8,2023-06-06,1,171.82,171.82
2512,1523,43,7,2026-01-01,1,131.87,131.87
2513,299,221,9,2023-10-14,3,222.88,668.64
2515,486,101,8,2023-01-07,3,171.82,515.46
2516,1182,174,7,2023-05-24,2,131.87,263.74
2517,1382,45,18,2023-09-22,2,126.38,252.76
2518,1162,6,14,2023-09-03,1,385.93,385.93
2519,786,128,8,2023-09-24,3,171.82,515.46
2520,1420,25,4,2023-04-09,3,246.02,738.06
2521,96,62,20,2023-07-27,1,244.08,244.08
2522,439,186,18,2023-05-25,3,126.38,379.14
2523,1451,255,5,2023-05-04,2,195.21,390.42
2524,762,270,1,2023-01-23,2,300.03,600.06
2525,1038,193,10,2023-12-18,3,134.30,402.90
2526,518,168,14,2026-01-01,3,385.93,1157.79
2527,31,203,9,2023-05-27,1,222.88,222.88
2528,357,61,14,2023-07-06,2,385.93,771.86
2529,252,89,19,2023-08-30,3,206.11,618.33
2530,301,126,8,2023-07-27,1,171.82,171.82
2532,676,86,20,2023-08-30,1,244.08,244.08
2533,2142,160,2,2023-05-14,1,181.61,181.61
2534,828,297,9,2023-01-21,2,222.88,445.76
2535,2060,31,9,2023-05-20,2,222.88,445.76
2536,1397,216,18,2023-01-09,2,126.38,252.76
2537,418,133,4,2023-03-15,2,246.02,492.04
2539,450,144,17,2023-05-09,1,343.71,343.71
2541,2050,168,1,2023-04-07,2,300.03,600.06
2542,1906,96,1,2023-10-23,1,300.03,300.03
2543,264,211,5,2023-08-16,1,195.21,195.21
2544,1894,256,1,2023-05-31,2,300.03,600.06
2545,1392,71,7,2023-03-04,2,131.87,263.74
2546,2051,100,11,2023-01-06,3,208.55,625.65
2547,2440,224,11,2023-05-18,3,208.55,625.65
2548,1863,251,2,2023-12-11,3,181.61,544.83
2549,1181,287,17,2023-11-27,1,343.71,343.71
2550,728,90,9,2023-02-01,3,222.88,668.64
2551,2082,45,9,2023-05-10,1,222.88,222.88
2552,2004,160,11,2023-09-24,2,208.55,417.10
2553,1042,229,16,2023-05-13,2,374.66,749.32
2554,1820,85,19,2023-03-08,2,206.11,412.22
2555,1285,39,18,2023-03-10,2,126.38,252.76
2556,238,180,11,2023-06-28,3,208.55,625.65
2557,636,216,7,2023-02-16,3,131.87,395.61
2558,1007,220,4,2023-03-15,1,246.02,246.02
2559,1375,18,5,2023-10-05,1,195.21,195.21

In [89]:
df_ord.query('order_id == 507')

,order_id,customer_id,product_id,order_date,quantity,price,total_amount
506,507,250,15,2023-06-28,1,413.17,413.17
2500,507,250,15,2023-06-28,1,413.17,413.17

Notamos que hay filas duplicadas que no aportan información.

In [90]:
df_ord = df_ord.loc[~df_ord.duplicated()].reset_index(drop=True).copy()

Hemos guardado una copia que omite los valores duplicados.

La tabla "Orders" ha sido limpiada.

<h2> Limpieza para la tabla "Products" </h2>

In [120]:
#Data frame "products"
df_pr = pd.read_csv(file_name2)
df_pr.head()

   product_id    category   price
0           1  electrnics  300.03
1           2    Clothing  181.61
2           3        Home  357.01
3           4    Clothing  246.02
4           5    Clothing  195.21

In [121]:
#Información de la tabla de productos
df_pr.info

<bound method DataFrame.info of     product_id     category   price
0            1   electrnics  300.03
1            2     Clothing  181.61
2            3         Home  357.01
3            4     Clothing  246.02
4            5     Clothing  195.21
5            6   electrnics  355.49
6            7  Electronics  131.87
7            8  Electronics  171.82
8            9     Clothing  222.88
9           10         Home  134.30
10          11       Beauty  208.55
11          12       Beauty  -50.00
12          13  Electronics  -50.00
13          14  Electronics  385.93
14          15     Clothing  413.17
15          16       Beauty  374.66
16          17  Electronics  343.71
17          18         Home  126.38
18          19         Home  206.11
19          20  Electronics  244.08>

In [122]:
#tipos de dato en la tabla "productos"
df_pr.dtypes

product_id      int64
category          str
price         float64
dtype: object

In [123]:
#Tamaño de la tabla 
df_pr.shape

(20, 3)

In [141]:
df_pr.describe(include=["str"])

        category
count         18
unique         5
top     Clothing
freq           5

In [124]:
df_pr.describe()

       product_id       price
count    20.00000   20.000000
mean     10.50000  224.941500
std       5.91608  130.342052
min       1.00000  -50.000000
25%       5.75000  162.440000
50%      10.50000  215.715000
75%      15.25000  346.655000
max      20.00000  413.170000

Notamos que hay valores negativos en "price". Los eliminamos y reiniciamos los indices.

In [128]:
df_pr = df_pr[df_pr['price']>0]

In [130]:
df_pr.reset_index(drop=True)

    product_id     category   price
0            1   electrnics  300.03
1            2     Clothing  181.61
2            3         Home  357.01
3            4     Clothing  246.02
4            5     Clothing  195.21
5            6   electrnics  355.49
6            7  Electronics  131.87
7            8  Electronics  171.82
8            9     Clothing  222.88
9           10         Home  134.30
10          11       Beauty  208.55
11          14  Electronics  385.93
12          15     Clothing  413.17
13          16       Beauty  374.66
14          17  Electronics  343.71
15          18         Home  126.38
16          19         Home  206.11
17          20  Electronics  244.08

Revisamos qué nombres están mal escritos en "categorias".

In [133]:
df_pr['category'].value_counts()

category
Clothing       5
Electronics    5
Home           4
electrnics     2
Beauty         2
Name: count, dtype: int64

In [135]:
df_pr.replace({"electrnics":"Electronics"})

    product_id     category   price
0            1  Electronics  300.03
1            2     Clothing  181.61
2            3         Home  357.01
3            4     Clothing  246.02
4            5     Clothing  195.21
5            6  Electronics  355.49
6            7  Electronics  131.87
7            8  Electronics  171.82
8            9     Clothing  222.88
9           10         Home  134.30
10          11       Beauty  208.55
13          14  Electronics  385.93
14          15     Clothing  413.17
15          16       Beauty  374.66
16          17  Electronics  343.71
17          18         Home  126.38
18          19         Home  206.11
19          20  Electronics  244.08

In [136]:
#Data frame "custumers"
df_cus = pd.read_csv(file_name3)
df_cus.head()

   customer_id   country signup_date
0            1    Mexico  2023-09-27
1            2    Mexico  2023-06-11
2            3  Colombia  2023-07-08
3            4    Mexico  2023-09-04
4            5    Mexico  2023-08-04

In [137]:
#Información de la tabla de productos
df_cus.info

<bound method DataFrame.info of      customer_id   country signup_date
0              1    Mexico  2023-09-27
1              2    Mexico  2023-06-11
2              3  Colombia  2023-07-08
3              4    Mexico  2023-09-04
4              5    Mexico  2023-08-04
..           ...       ...         ...
295          296  Colombia  2023-11-07
296          297  Colombia  2023-10-29
297          298       USA  2023-02-01
298          299       USA  2023-02-24
299          300    Mexico  2023-12-18

[300 rows x 3 columns]>

In [138]:
df_cus.dtypes

customer_id    int64
country          str
signup_date      str
dtype: object

In [139]:
df_cus.shape

(300, 3)

In [140]:
df_cus.describe()

       customer_id
count   300.000000
mean    150.500000
std      86.746758
min       1.000000
25%      75.750000
50%     150.500000
75%     225.250000
max     300.000000

In [143]:
df_cus.describe(include = ["str"])

       country signup_date
count      290         300
unique       4         208
top     Mexico  2023-10-10
freq       107           5

In [144]:
df_cus["country"].value_counts()

country
Mexico      107
Colombia     97
USA          81
Mx            5
Name: count, dtype: int64

Estandarizamos los nombres de los paises:

In [147]:
df_cus.replace({"Mx":"Mexico"})

     customer_id   country signup_date
0              1    Mexico  2023-09-27
1              2    Mexico  2023-06-11
2              3  Colombia  2023-07-08
3              4    Mexico  2023-09-04
4              5    Mexico  2023-08-04
..           ...       ...         ...
295          296  Colombia  2023-11-07
296          297  Colombia  2023-10-29
297          298       USA  2023-02-01
298          299       USA  2023-02-24
299          300    Mexico  2023-12-18

[300 rows x 3 columns]

In [145]:
df_cus["signup_date"].value_counts()

signup_date
2023-10-10    5
2023-03-24    4
2023-12-04    4
2023-03-14    4
2023-06-17    3
             ..
2023-02-21    1
2023-12-10    1
2023-10-29    1
2023-02-01    1
2023-02-24    1
Name: count, Length: 208, dtype: int64

Verificamos que no haya fechas incorrectas:

In [148]:
df_cus["signup_date"] = pd.to_datetime(df_cus["signup_date"])

In [151]:
len(df_cus[df_cus["signup_date"] > pd.Timestamp.today()])

0

No hay fechas inconsistentes